#!/usr/bin/env python

"""
Calculates the edit distance/string similiarity between entries of two columns
in a .tsv file, with each row being passed row-by-row through stdin.

@author: Hardik
"""

import argparse
import jellyfish as jf
import sys


# Edit distance functions in jellyfish.
DISTANCE_FUNCTIONS = [
	'damerau_levenshtein_distance',
	'hamming_distance',
	'jaro_distance',
	'jaro_winkler',
	'levenshtein_distance'
]


def main():
	parser_description = ("Calculates the edit distance/string "
		"similiarity between entries of two columns in a .tsv file, "
		"with each row being passed row-by-row through stdin.")
	parser = argparse.ArgumentParser(description=parser_description)

	parser.add_argument('method',
		help="Edit distance function (One of " +
			', '.join(DISTANCE_FUNCTIONS) + ")")
	parser.add_argument('-f', '--first_word_idx', help="First word index",
		type=int, default=0)	
	parser.add_argument('-s', '--second_word_idx', help="Second word index",
		type=int, default=1)

	args = parser.parse_args()

	if args.method not in DISTANCE_FUNCTIONS:
		raise ValueError("Invalid distance function (Must be one of " +
			', '.join(DISTANCE_FUNCTIONS) + ")")

	edit_distance = getattr(jf, args.method)

	try:
		while True:
			row = raw_input().split('\t')
			word1 = row[args.first_word_idx]
			word2 = row[args.second_word_idx]
			word1_dec = word1.decode('utf-8')
			word2_dec = word2.decode('utf-8')
			print '\t'.join(row).strip() + '\t' + str(edit_distance(word1_dec, word2_dec))
	except EOFError:
		pass


if __name__ == '__main__':
	main()

