#!/bin/bash

usage() {
	echo -e "Usage:$0 <Output path to .tar.gz> <Input folder path>"
}

# Output archive path (Filename should have extension .tar.gz)
output=$1
# Input directory
input=$2

if [[ ! $# -eq 2 ]]
then
	usage
	exit 1
fi

tar czf $output $input
