#!/bin/bash

# Uncompress a given gzipped folder.

usage() {
	echo -e "Usage: $(basename $0) <Input path to .tar.gz>"
}

# Input .tar.gz path.
input=$2

if [[ ! $# -eq 1 ]]
then
	usage
	exit 1
fi

tar -xzvf $input
